Fixes Issue #42 - Allow users to enlarge images in player
ucfopen/this-or-that-materia-widget pull request #46
Opened 2022-04-13 21:10 UTC by cayb0rg

2022-04-14 14:09 UTC, clpetersonucf requested changes
That was quick - and easy! The changes look great, here are four small follow-ups I'd like to see included in this pull request as well:
- The non-expanded version of images are still being stretched to fill the container, instead of having their aspect ratios preserved. This isn't apparent in the dev kit since all the images provided have aspect ratios that fit the container. You'll probably have to install the widget to your local copy of Materia to test this out.
- Images in the expanded lightbox should be centered instead of left-justified
- The lightbox for images doesn't have to be an iframe - we're only doing that for video because its embedding content from YouTube or Vimeo
- The instructional Designer who requested these changes was also interested in optional feedback for _correct_ answers as well as incorrect answers. This will require modifying the creator as well as the question set (qset) structure for the widget, which requires some care. I'm happy to go over this in more detail.

2022-04-14 14:09 UTC, clpetersonucf commented on src/player.html
> +					<iframe class="lightbox-iframe" ng-if="answers[lightboxTarget].options.asset.type == 'video' || answers[lightboxTarget].options.asset.type == 'image'" ng-src="{{answers[lightboxTarget].options.a
Like I mentioned in my review comments, this should probably be a `div` instead of an `iframe` for the image version.

2022-04-29 16:12 UTC, ljoks requested changes
Really nice job overall, especially catching the backwards compatibility! 
Two things I noticed that need fixing: 

1. Although the fields say feedback is an optional field (for both correct and incorrect), trying to save while leaving them blank causes an error. see `src/services/srv-creator.js` lines 44 & 58
2. When you go to update an existing widget, feedback values are not populated in the fields for correct or incorrect

2022-05-09 19:56 UTC, clpetersonucf requested changes
I can confirm the behaviors LJ mentioned. In addition, I'm also noticing that while the player preserves image aspect ratios, the creator does not. Ideally, the aspect ratios are preserved in both, so images don't look stretched or distorted to the user as soon as they upload them.

2022-05-18 14:27 UTC, clpetersonucf approved these changes
This looks good and works great. I ended up adding the backwards-compatibility checks for the old feedback location, just because they were small changes.

2022-05-19 17:26 UTC, merged