Implemented question bank functionality
ucfopen/this-or-that-materia-widget pull request #65
Opened 2024-01-12 18:38 UTC by dmols

Question bank is now fully implemented for this widget. I added a good amount of styling to the dialog but please let me know if you have any suggestions to make it fit the theme of the widget a little better, or any in general to make the question bank function better!

2024-01-16 16:45 UTC, dmols commented
Fixed most of the issues addressed in the review, minus the UI style changes. I'm thinking you mean the QB button needs to match the 'randomizeOrder' button, but wasn't sure. Happy to tag-team the CSS changes needed to make this visually ready for merge.

2024-01-23 14:49 UTC, clpetersonucf commented on src/creator.html
> +					<strong>Enable question bank? </strong>
Since this is associated with an input selection, prefer `<label>`. Remember that semantic HTML is always ideal.

2024-02-13 22:17 UTC, dmols commented
All the requested changes have been made. Only issue I find is that the value in `num-input` keeps getting bolded. Not sure if it's the screen size making it seem that way or if there's CSS at play changing the font weight, but I can't find anything of the sort.

2024-02-23 19:57 UTC, clpetersonucf requested changes
This is very, very close to being ready. Nice job incorporating all the feedback I've given you :+1:

The only thing I'm hung up on: enabling the question bank randomizes the questions, but that's not communicated anywhere in the creator. The question bank dialog should probably include a message to indicate that questions will be randomized.

2024-04-15 20:38 UTC, clpetersonucf approved these changes
All requested changes have been made. This looks good, and works great. I might do some small styling adjustments, but there's nothing that should stop this PR from being approved.

2024-04-15 20:38 UTC, merged